/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store.manager;
import store.QuanLy;
import database.NhanvienDB;
import store.data.NhanVien;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hoang
 */
public class QuanLyNhanVien extends javax.swing.JFrame {
    public QuanLy quanLy;
    /**
     * Creates new form TimeKiem
     */
    public QuanLyNhanVien() {
        initComponents();
    }
    
     // Làm mới bảng mỗi khi có sự kiện thêm/sửa/xoá/tìm kiếm
    public void refresh(){
        inputError.setVisible(false);
        String term = searchInput.getText();
        List<NhanVien> list = NhanvienDB.getALL(term);
        DefaultTableModel tableModel = (DefaultTableModel) contentTable.getModel();
        tableModel.setRowCount(0);
        list.forEach((nv) -> {
            tableModel.addRow(new Object[]{
                nv.getMaNV(), nv.getHoTen(), nv.getDiaChi(),
                nv.getNgaySinh(), nv.getGioiTinh(), nv.getSdt()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTable = new javax.swing.JTable();
        searchInput = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        maInput = new javax.swing.JTextField();
        hoTenInput = new javax.swing.JTextField();
        diaChiInput = new javax.swing.JTextField();
        ngaySinhInput = new javax.swing.JTextField();
        gioiTinhInput = new javax.swing.JTextField();
        sdtInput = new javax.swing.JTextField();
        inputError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");

        back.setText("trở về");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        contentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Địa chỉ", "Ngày sinh", "Giới tính", "sdt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(contentTable);
        refresh();

        jButton2.setText("Lưu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tìm kiếm 🔍");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("➕");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        maInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maInputActionPerformed(evt);
            }
        });

        hoTenInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoTenInputActionPerformed(evt);
            }
        });

        diaChiInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaChiInputActionPerformed(evt);
            }
        });

        ngaySinhInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinhInputActionPerformed(evt);
            }
        });

        gioiTinhInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gioiTinhInputActionPerformed(evt);
            }
        });

        sdtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtInputActionPerformed(evt);
            }
        });

        inputError.setForeground(new java.awt.Color(255, 0, 51));
        inputError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputError.setText("Hãy điền đủ mã và họ tên");

        jButton1.setText("Xoá");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(684, 684, 684))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputError, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(467, 467, 467)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoTenInput, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diaChiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngaySinhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gioiTinhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sdtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoTenInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaChiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngaySinhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gioiTinhInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        inputError.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // nút trở về
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.quanLy.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    // nút lưu
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int rows = contentTable.getRowCount();
        for(int i=0;i<rows;i++){
            String ma = contentTable.getValueAt(i, 0).toString();
            String hoTen = contentTable.getValueAt(i, 1).toString();
            String diaChi = contentTable.getValueAt(i, 2).toString();
            String ngaySinh = contentTable.getValueAt(i, 3).toString();
            String gioiTinh = contentTable.getValueAt(i, 4).toString();
            String sdt = contentTable.getValueAt(i, 5).toString();
            NhanvienDB.update(new NhanVien(ma, hoTen, diaChi, ngaySinh, gioiTinh, sdt));
        }
        refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    // nút thêm
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String maNV = maInput.getText();
        String hoTen = hoTenInput.getText();
        if(maNV == null || hoTen == null || maNV.length() == 0 || hoTen.length() == 0){
            inputError.setVisible(true);
            return;
        }
        String diaChi = diaChiInput.getText();
        String ngaySinh = ngaySinhInput.getText();
        String gioiTinh = gioiTinhInput.getText();
        String sdt = sdtInput.getText();
        NhanvienDB.insert(new NhanVien(maNV, hoTen, diaChi, ngaySinh, gioiTinh, sdt));
        this.refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    // input mã nhân viên
    private void maInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maInputActionPerformed

    // input họ tên
    private void hoTenInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoTenInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoTenInputActionPerformed

    // input địa chỉ
    private void diaChiInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaChiInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaChiInputActionPerformed

    //input ngày sinh
    private void ngaySinhInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinhInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinhInputActionPerformed

    // input giới tính
    private void gioiTinhInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gioiTinhInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gioiTinhInputActionPerformed

    // input số điện thoại
    private void sdtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtInputActionPerformed

    // nút xoá
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = contentTable.getSelectedRow();
        String ma = contentTable.getValueAt(row, 0).toString();
        NhanvienDB.delete(ma);
        refresh();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // nút tìm kiếm
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable contentTable;
    private javax.swing.JTextField diaChiInput;
    private javax.swing.JTextField gioiTinhInput;
    private javax.swing.JTextField hoTenInput;
    private javax.swing.JLabel inputError;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maInput;
    private javax.swing.JTextField ngaySinhInput;
    private javax.swing.JTextField sdtInput;
    private javax.swing.JTextField searchInput;
    // End of variables declaration//GEN-END:variables
}
